#!/bin/bash

git clean -fd
git checkout gh-pages
git pull -s ours
git merge --strategy=theirs master
git commit -am "automatic commit"
./build
git push origin gh-pages
git checkout .
git checkout master
